const imgArtists = [
  {
    id: 1,
    alt: 'imagen-George-Harrison',
    url: 'https://pt.wikipedia.org/wiki/George_Harrison',
    img: 'https://hqrock.files.wordpress.com/2011/11/george-harrison-let-it-be-photo.jpg',
    description: 'George Harrison foi um guitarrista, cantor, compositor, produtor musical e cinematográfico britânico que obteve fama internacional como guitarrista dos Beatles.',
    nascimento: '25 de fevereiro de 1943, 12 Arnold Grove',
    falecimento: '29 de novembro de 2001, Los Angeles, Califórnia, EUA',
  },
  {
    id: 3,
    alt: 'imagen-Tom-Petty',
    url: 'https://pt.wikipedia.org/wiki/Tom_Petty',
    img: 'https://img.estadao.com.br/resources/jpg/8/5/1607970451558.jpg',
    description: 'Tom Petty, nome artístico de Thomas Earl Petty foi um compositor e cantor estadunidense de rock. Iniciou na banda The Epics e, foi fundador e vocalista da banda Tom Petty and the Heartbreakers. Também foi integrante do supergrupo Traveling Wilburys.',
    nascimento: '20 de outubro de 1950, Gainesville, Flórida, EUA',
    falecimento: '2 de outubro de 2017, Santa Mônica, Califórnia, EUA',
  },
  {
    id: 5,
    alt: 'imagen-David-Crosby',
    url: 'https://pt.wikipedia.org/wiki/David_Crosby',
    img: 'https://www.rollingstone.com/wp-content/uploads/2018/06/rs-183153-79590801.jpg?crop&width=440',
    description: 'David Van Cortlandt Crosby é um guitarrista, cantor, compositor e produtor dos Estados Unidos. Além de sua carreira solo, também é conhecido por ter sido um dos fundadores das bandas The Byrds, Crosby, Stills & Nash e Crosby, Stills, Nash & Young e CPR.',
    nascimento: '14 de agosto de 1941 (idade 80 anos), Los Angeles, Califórnia, EUA',
    falecimento: '',
  },
  {
    id: 13,
    alt: 'imagen-John-Lennon',
    url: 'https://pt.wikipedia.org/wiki/John_Lennon',
    img: 'https://revistabula.com/wp/wp-content/uploads/2021/12/john-lennon.jpg',
    description: 'John Winston Ono Lennon MBE foi um cantor, compositor e ativista da paz britânico que fundou os Beatles, a banda de maior sucesso comercial na história da música popular. Sua parceria de composição com o colega de banda Paul McCartney foi uma das mais célebres da história da música.',
    nascimento: '9 de outubro de 1940, Liverpool, Reino Unido',
    falecimento: '8 de dezembro de 1980, Edifício Dakota, Nova Iorque, Nova York, EUA',
  },
  {
    id: 14,
    alt: 'imagen-Jet-Black',
    url: 'https://pt.wikipedia.org/wiki/The_Jet_Blacks',
    img: 'https://quiabodoido.com/wp-content/uploads/2021/05/the-jet-blacks.jpg',
    description: 'The Jet Blacks foi uma banda de Rock Pop brasileira, fundada no início dos anos 1960. A banda teve várias formações e obteve relativo sucesso na década de 1960 se apresentando com nomes conhecidos da Jovem Guarda.',
    nascimento: '',
    falecimento: '',
  },
  {
    id: 15,
    alt: 'imagen-Dave-Greenfield',
    url: 'https://en.wikipedia.org/wiki/Dave_Greenfield',
    img: 'https://static01.nyt.com/images/2020/05/09/obituaries/07GREENFIELD/07GREENFIELD-mobileMasterAt3x.jpg',
    description: 'David Paul Greenfield foi um tecladista, cantor e compositor inglês que foi membro da banda de rock The Stranglers. Ele se juntou à banda em 1975, um ano depois de sua formação, e tocou com eles por 45 anos até sua morte.',
    nascimento: '29 de março de 1949, Brighton, Reino Unido',
    falecimento: '3 de maio de 2020',
  },
  {
    id: 16,
    alt: 'imagen-Lou-Reed',
    url: 'https://pt.wikipedia.org/wiki/Lou_Reed',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Lou_Reed_%285900407225%29.jpg',
    description: 'Lewis Allen "Lou" Reed foi um cantor, guitarrista e compositor norte-americano. Foi considerado o 81.º melhor guitarrista de todos os tempos pela revista norte-americana Rolling Stone. Juntamente com John Cale, ele fundou a banda produzida por Andy Warhol, The Velvet Underground.',
    nascimento: '2 de março de 1942, Nova Iorque, Nova York, EUA',
    falecimento: '27 de outubro de 2013, Amagansett, Nova York, EUA',
  },
  {
    id: 17,
    alt: 'imagen-John-Cale',
    url: 'https://pt.wikipedia.org/wiki/John_Cale',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/John_Cale_%282006%29.jpg/1200px-John_Cale_%282006%29.jpg',
    description: 'John Davies Cale, é um músico britânico que depois da sua saída da banda de vanguarda The Velvet Underground, em 1968, iniciou uma carreira solo.',
    nascimento: '9 de março de 1942 (idade 80 anos), Garnant, Reino Unido',
    falecimento: '',
  },
  {
    id: 18,
    alt: 'imagen-Sterling-Morrison',
    url: 'https://pt.wikipedia.org/wiki/Sterling_Morrison',
    img: 'https://images.mubicdn.net/images/cast_member/87471/cache-420891-1553034470/image-w856.jpg?size=800x',
    description: 'Holmes Sterling Morrison, Jr. foi um dos fundadores e membro da banda de rock The Velvet Underground, tocava guitarra e, ocasionalmente, baixo.',
    nascimento: '29 de agosto de 1942, East Meadow, Nova York, EUA',
    falecimento: '30 de agosto de 1995, Poughkeepsie, Nova York, EUA',
  },
  {
    id: 19,
    alt: 'imagen-Moe-Tucker',
    url: 'https://pt.wikipedia.org/wiki/Maureen_Tucker',
    img: 'https://www.rollingstone.com/wp-content/uploads/2021/10/The_Velvet_Underground_Photo_0107.jpg?resize=1800,1200&w=1800',
    description: 'Maureen Ann Tucker, também conhecida como Mo Tucker, é uma instrumentista conhecida pelo seu trabalho como baterista do grupo de rock The Velvet Underground e por seu visual andrógino.',
    nascimento: '26 de agosto de 1944 (idade 77 anos)',
    falecimento: '',
  }
]

export default imgArtists;
